#!/usr/bin/env bash
# Regenerates the derived reference tables under docs/reference/ from the
# actual current repo state, so they can't silently drift from reality the
# way hand-maintained tables do.
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

OUT="$ROOT/docs/reference/PACKAGE_INDEX.md"

{
  echo "# Package index"
  echo
  echo "Regenerated by ./scripts/update_docs.sh - do not hand-edit the table below."
  echo
  echo "| Path | Type | pubspec description |"
  echo "|---|---|---|"
  for pubspec in "$ROOT"/apps/*/pubspec.yaml "$ROOT"/packages/*/pubspec.yaml "$ROOT"/modules/*/pubspec.yaml "$ROOT"/showcase/pubspec.yaml; do
    [ -f "$pubspec" ] || continue
    dir="$(dirname "$pubspec")"
    rel="${dir#"$ROOT"/}"
    type="Pure Dart"
    grep -q 'flutter:' "$pubspec" && type="Flutter"
    desc="$(grep '^description:' "$pubspec" | sed 's/^description: *//' | head -1)"
    echo "| \`$rel\` | $type | ${desc:-_(no description)_} |"
  done
} > "$OUT"

echo "Updated $OUT"
